# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # build app
      - run: npm run build-prod
      # run tests!
      - run: npm run test 

  deploy:
    machine: 
      enabled: true 
    working_directory: ~/repo
    filters:
      branches:
        only: tukuna30/release-26/05/2018
      
    steps:
      - run:
          name: 'Execute deploy script'
          command: |
           ssh ec2-user@ec2-13-126-162-20.ap-south-1.compute.amazonaws.com "cd test_aws && git pull && git checkout tukuna30/release-26/05/2018 && npm install && npm run build-prod && pm2 startOrRestart ecosystem.config.js --env production"

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy: 
          requires:
            - build

